export const datauser=[
  {
    id: 1,
    firstName: "Leanne Graham",
    lastName: "Bret",
    email: "Sincere@april.biz",
    street: "Kulas Light",
    suite: "Apt. 556",
    city: "Gwenborough",
    zipcode: "92998-3874",
    phone: "1-770-736-8031 x56442",
    website: "hildegard.org",
  },
  {
    id: 2,
    firstName: "Ervin Howell",
    lastName: "Antonette",
    email: "Shanna@melissa.tv",
    street: "Victor Plains",
    suite: "Suite 879",
    city: "Wisokyburgh",
    zipcode: "90566-7771",
    phone: "010-692-6593 x09125",
    website: "anastasia.net",
  },
  {
    id: 3,
    firstName: "Clementine Bauch",
    lastName: "Samantha",
    email: "Nathan@yesenia.net",
    street: "Douglas Extension",
    suite: "Suite 847",
    city: "McKenziehaven",
    zipcode: "59590-4157",
    phone: "1-463-123-4447",
    website: "ramiro.info",
  },
  {
    id: 4,
    firstName: "Patricia Lebsack",
    lastName: "Karianne",
    email: "Julianne.OConner@kory.org",
    street: "Hoeger Mall",
    suite: "Apt. 692",
    city: "South Elvis",
    zipcode: "53919-4257",
    phone: "493-170-9623 x156",
    website: "kale.biz",
  },
  {
    id: 5,
    firstName: "Chelsey Dietrich",
    lastName: "Kamren",
    email: "Lucio_Hettinger@annie.ca",
    street: "Skiles Walks",
    suite: "Suite 351",
    city: "Roscoeview",
    zipcode: "33263",
    phone: "(254)954-1289",
    website: "demarco.info",
  },
  {
    id: 6,
    firstName: "Mrs. Dennis Schulist",
    lastName: "Leopoldo_Corkery",
    email: "Karley_Dach@jasper.info",
    street: "Norberto Crossing",
    suite: "Apt. 950",
    city: "South Christy",
    zipcode: "23505-1337",
    phone: "1-477-935-8478 x6430",
    website: "ola.org",
  },
  {
    id: 7,
    firstName: "Kurtis Weissnat",
    lastName: "Elwyn.Skiles",
    email: "Telly.Hoeger@billy.biz",
    street: "Rex Trail",
    suite: "Suite 280",
    city: "Howemouth",
    zipcode: "58804-1099",
    phone: "210.067.6132",
    website: "elvis.io",
  },
  {
    id: 8,
    firstName: "Nicholas Runolfsdottir V",
    lastName: "Maxime_Nienow",
    email: "Sherwood@rosamond.me",
    street: "Ellsworth Summit",
    suite: "Suite 729",
    city: "Aliyaview",
    zipcode: "45169",
    phone: "586.493.6943 x140",
    website: "jacynthe.com",
  },
  {
    id: 9,
    firstName: "Glenna Reichert",
    lastName: "Delphine",
    email: "Chaim_McDermott@dana.io",
    street: "Dayna Park",
    suite: "Suite 449",
    city: "Bartholomebury",
    zipcode: "76495-3109",
    phone: "(775)976-6794 x41206",
    website: "conrad.com",
  },

  {
    id: 10,
    firstName: "Clementina DuBuque",
    lastName: "Moriah.Stanton",
    email: "Rey.Padberg@karina.biz",
    street: "Kattie Turnpike",
    suite: "Suite 198",
    city: "Lebsackbury",
    zipcode: "31428-2261",
    phone: "024-648-3804",
    website: "ambrose.net",
  },
];
